use_nerdfont = false
volnorm = true
default_keybindings = false
bitrate = 96
gapless = true

[keybindings]
"1" = "focus library"
"2" = "focus queue"
"Ctrl+b" = "move up 10"
"Ctrl+d" = "move down 5"
"Ctrl+e" = "move down 1"
"Ctrl+f" = "move down 10"
"Ctrl+l" = "update"
"Ctrl-n" = "jump next"
"Ctrl+o" = "back"
"Ctrl-p" = "jump previous"
"Ctrl+u" = "move up 5"
"Ctrl+y" = "move up 1"
"Enter" = "play"
"g" = "move top"
"?" = "help"
"h" = "move left 1"
"j" = "move down 1"
"k" = "move up 1"
"l" = "move right 1"
">" = "next"
"o" = "open selected"
"<" = "previous"
"q" = "queue"
"r" = "repeat"
"Shift+g" = "move bottom"
"Shift+h" = "seek -10000"
"Shift+l" = "seek +10000"
"Shift+q" = "quit"
"Shift+s" = "save queue"
"Space" = "playpause"
"s" = "save"
"-" = "voldown 5"
"+" = "volup 5"
"z" = "shuffle"
